lib/pipeline.rb, lib/pipeline/options.rb, lib/pipeline/reporters.rb, lib/pipeline/tasks/bundle-audit.rb, lib/pipeline/tasks/findsecbugs.rb, lib/pipeline/tasks/npm.rb, lib/pipeline/tasks/nsp.rb, lib/pipeline/tasks/pmd.rb, lib/pipeline/tasks/retirejs.rb, lib/pipeline/util.rb, lib/pipeline/version.rb
Allow passing logfile as filename or ruby file object to write message/command stderr to.  Also adds timestamps to log output.
=> logging updates

DOCKER.md, OPTIONS.md, docker/glue/Dockerfile, lib/glue.rb, lib/glue/filters/jira_one_time_filter.rb, lib/glue/finding.rb, lib/glue/options.rb, lib/glue/reporters/jira_reporter.rb, lib/glue/tasks/owasp-dep-check.rb
Doc updates and fixes for OWASP Dependency Check. Miscellaneous cleanup.
=> Doc updates and fixes for OWASP Dependency Check.

lib/glue/options.rb, lib/glue/tasks/burp.rb
Initial revision of support to process Burp reports in XML format.
=> Adding Burp report processor.

lib/glue/tasks/contrast.rb
Minor upgrades to the bidirectional link between Contrast and JIRA. Highlights:
- Enhancements for Contrast <-> JIRA link
- Switch to Glue.debug for logging
- Improved logging
=> Adding enhancements for Contrast <-> JIRA link

docker/glue/Dockerfile, lib/glue/options.rb, lib/glue/tasks/owasp-dep-check.rb
This PR adds options to Glue to support logging and suppression files for OWASP Dependency Check. Both of these are pass-through options, so this PR just exposes via Glue those options that already exist in Dependency Check.
=> Adding options for Dependency Check logging and suppression.

docker/glue/Dockerfile, lib/glue/tasks/trufflehog.rb
Adds the TruffleHog scanner (https://github.com/dxa4481/truffleHog) via a fork that scans only local directories.
=> Adding TruffleHog scanner.

lib/glue/filters/contrast_severity_filter.rb, lib/glue/finding.rb, lib/glue/options.rb, lib/glue/tasks/base_task.rb, lib/glue/tasks/contrast.rb
This PR enables enhanced filtering for Contrast. Two new command-line options are added that allow filtering by minimum severity, as well as any of the properties exposed by the Contrast endpoint (e.g. servers).
=> Enhanced filtering for Contrast

lib/glue/finding.rb, lib/glue/reporters/base_reporter.rb, lib/glue/reporters/csv_reporter.rb, lib/glue/reporters/json_reporter.rb
This PR improves the quality of JSON and CSV reporting. In particular:
- CSV output is now usable by popular spreadsheets (e.g. Excel)
- JSON output is now parseable by the Ruby JSON library
=> Improving JSON and CSV reporting

lib/glue/tasks.rb
Do not check if task is supported if the task does not support the current stage
=> first check if task match stage and then if it supported

lib/glue/options.rb, lib/glue/tasks/checkmarx.rb
close #55 
Added:
* Enable Checkmarx task
* Added optional Checkmarx options, including the path to CxCli
* Check if the scan succeeded (by looking if the report was created)
* Ignore results that marked as "Not exploitable" on Checkmarx Web Portal (see the original issue for details)
=> improved Checkmarx task to support all Checkmarx features

lib/glue.rb, lib/glue/tasks/checkmarx.rb
=> added fatal log level

lib/glue/options.rb, lib/glue/reporters/jira_reporter.rb, lib/glue/tasks/contrast.rb
This PR adds the ability to optionally link created issues to a JIRA epic via the JIRA reporter.
=> JIRA epics

lib/glue.rb, lib/glue/options.rb, lib/glue/tasks/owasp-dep-check.rb
Support for OWASP Dependency Check for Scala via the Dependency Check plugin for sbt.
=> Scala Dependency Check via sbt plugin

docker/glue/Dockerfile
Adding missing Dockerfile with Scala tools.
=> Adding missing Dockerfile with Scala tools

TOOLS.md
=> updated tools.md checkmarx section

lib/glue/tasks/snyk.rb
- Add exception handling
- Move some functionality to private methods
I made these changes after writing the specs,
so I think everything is okay here.
I didn't change the implementation of 'supported?'
but eventually we may want to move away from using
'find_executable0'.
=> Refactor snyk.rb

lib/glue/tasks/zap.rb
=> added zap evidence to the details of finding

lib/glue/tasks/zap.rb
I think it should be just bigger than 2.4, but for now, I just added 2.7
=> added support for zap 2.7

codefresh.yaml, spec/spec_helper.rb
Simple integration that just pushes to dockerhub, later we should add running the test - currently they are not passing so I did not do it.
=> added codefresh config file

spec/awsscout_spec.rb, spec/tasks/trufflehog/trufflehog_spec.rb
I want to run the tests in the CI, currently, there are 2 specs that fails all the tests:
* TruffleHog tests failed because TruffleHog is not installed - this should be solved either with mock or with Docker as integration test IMO
* AWSScout tests failed from unknown reason, this is the error:
```
An error occurred while loading ./spec/awsscout_spec.rb.
Failure/Error:
Open3.popen3(*splat) do |stdin, stdout, stderr, wait_thr|
if $logfile and report
while line = stderr.gets do
$logfile.puts line
end
end
return stdout.read.chomp
Errno::ENOENT:
No such file or directory - Scout2
Finished in 0.00028 seconds (files took 2.95 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```
For now I'm commenting them out so I could add the tests into the CI
=> comment out failing tests

README.md
We can add more from [shields.io](https://shields.io/)
=> added some badges to readme

.travis.yml, README.md
The credentials are missing, so the build fails
=> temporary disable dockerhub deployment

docs/dynamic_task.md, lib/glue/mappings/zaproxy.json, spec/tasks/dynamic/dynamic_spec.rb, spec/tasks/dynamic/targets/tools_samples/zaproxy.json
Now you can use the dynamic task to process Zap's reports.
To use
=> added zap pattern for dynamic task

lib/glue/mappings/snyk.json, spec/tasks/dynamic/dynamic_spec.rb, spec/tasks/dynamic/targets/tools_samples/snyk.json
A lot simpler than the current Snyk task :)
=> Added snyk support to dynamic task

PLAYGROUND.md
Relates to questions asked in #169
=> Adding Docker example as well as correcting --finding-file-path
